#!/bin/sh

SELF=$(cd $(dirname $0); pwd)
cd ${SELF}/..

# fetch repository
git --git-dir=.git pull origin master

# generate HTML
sh bin/hugo

# restart docker container
cd docker/
docker-compose down
docker-compose up -d

exit 0
