#!/bin/sh

cd ~/workspace/memo.ontheroad.jp/hugo-memo-dev

# fetch repository
git --git-dir=.git pull origin master

# generate HTML
sh bin/hugo

# restart docker container
docker-compose -f docker/docker-compose.yml down
docker-compose -f docker/docker-compose.yml up -d

exit 0
